# --------------------------
# Basic Site Settings
# --------------------------

theme: jekyll-theme-chirpy

lang: ko-KR
timezone: Asia/Seoul

title: HyungSeok Kim
tagline: Knowledge, Notes & Experiments
description: Personal tech & research blog

url: "https://khselect.github.io"
baseurl: ""

# --------------------------
# Author / Social
# --------------------------

github:
  username: khselect

social:
  name: HyungSeok Kim
  email: sielain@ictr.or.kr
  links:
    - https://github.com/khselect

# --------------------------
# Chirpy Required Defaults
# --------------------------

toc: true
paginate: 10

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      permalink: /posts/:title/

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"

# --------------------------
# Pagination
# --------------------------

paginate: 10
toc: true

# --------------------------
# Archives (중요)
# --------------------------

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

